import { describe, expect, it } from "vitest";
import {
  POLICY_BLOCK_KEY,
  renderAgentsPolicyBlock,
  renderClaudePolicyBlock,
  renderCodexCatalog,
  renderCodexSkillMetadata,
  renderProjection,
  renderSkillFile,
} from "../../src/core/render.ts";
import { displayName, type SkillSource } from "../../src/core/skill.ts";
import type { Manifest } from "../../src/core/manifest.ts";
import { fixtureConfiguration, fixtureSkills, fixtureInstallation } from "../fixtures/corpus.ts";

function manifestWith(overrides: Partial<Manifest>): Manifest {
  return { ...fixtureConfiguration, ...overrides };
}

function fixtureSkillAt(index: number): SkillSource {
  const skill = fixtureSkills[index];
  if (skill === undefined) throw new Error(`fixture skill at index ${index} is missing`);
  return skill;
}

const deliveryReview = (): SkillSource => fixtureSkillAt(0);
const grilling = (): SkillSource => fixtureSkillAt(1);

describe("renderSkillFile", () => {
  it("renders frontmatter and body with one trailing newline", () => {
    const file = renderSkillFile(fixtureSkillAt(0));
    expect(file).toBe(
      [
        "---",
        'name: "delivery-review"',
        'description: "Review committed work against the ticket contract."',
        "---",
        "",
        "# Delivery Review",
        "",
        "Read the commit range and the ticket, then report findings.",
        "",
      ].join("\n"),
    );
  });

  it("normalizes the trailing newline regardless of input body", () => {
    const file = renderSkillFile({
      name: "x",
      description: "d",
      class: "discipline",
      activation: "implicit",
      body: "body",
    });
    expect(file.endsWith("body\n")).toBe(true);
  });
});

describe("renderCodexSkillMetadata", () => {
  it("expresses the activation policy once per harness convention", () => {
    expect(renderCodexSkillMetadata(grilling())).toBe(
      [
        "interface:",
        '  display_name: "Grilling"',
        '  short_description: "Grill the operator about a plan before building it."',
        "",
      ].join("\n"),
    );
    expect(renderCodexSkillMetadata(deliveryReview())).toBe(
      [
        "interface:",
        '  display_name: "Delivery Review"',
        '  short_description: "Review committed work against the ticket contract."',
        "policy:",
        "  allow_implicit_invocation: false",
        "",
      ].join("\n"),
    );
  });
});

describe("renderCodexCatalog", () => {
  it("lists installed skills sorted by name with their activation", () => {
    // Input order is the caller's selection; the projection sorts first.
    expect(renderCodexCatalog([deliveryReview(), grilling()])).toBe(
      [
        "version: 1",
        "skills:",
        '  - name: "delivery-review"',
        '    path: ".agents/skills/delivery-review"',
        '    class: "stage"',
        '    activation: "explicit"',
        '  - name: "grilling"',
        '    path: ".agents/skills/grilling"',
        '    class: "discipline"',
        '    activation: "implicit"',
        "",
      ].join("\n"),
    );
  });
});

describe("renderAgentsPolicyBlock", () => {
  it("renders installed names without duplicating harness discovery metadata", () => {
    const block = renderAgentsPolicyBlock([grilling(), deliveryReview()]);
    expect(block).toContain("- stage: delivery-review");
    expect(block).toContain("- discipline: grilling");
    // The description already ships in each harness's per-skill metadata;
    // a third copy in the always-loaded block bought nothing (exam R2).
    expect(block).not.toContain("Review committed work against the ticket contract.");
    expect(block.startsWith("> Owned region, generated by the greenline CLI. Do not edit.")).toBe(
      true,
    );
  });

  it("inserts the supplied release protocol unchanged before the generated roster", () => {
    const guide = "# Protocol\nOne current source.\n";
    const block = renderAgentsPolicyBlock([grilling()], [], guide);
    expect(block).toContain(guide.trim());
    expect(block.indexOf(guide.trim())).toBeLessThan(block.indexOf("## Installed skills"));
  });

  it("renders the intent-to-skill table, dropping excluded skills' rows", () => {
    const intents = [
      { intent: "Shape a change", skills: ["grill-with-docs"] },
      { intent: "Review committed work", skills: ["delivery-review"] },
    ];
    const block = renderAgentsPolicyBlock([grilling(), deliveryReview()], intents);
    expect(block).toContain("| What you are doing | Skill to load |");
    expect(block).toContain("| Review committed work | delivery-review |");
    // The row whose skill is not installed drops entirely.
    expect(block).not.toContain("Shape a change");
  });
});

describe("renderClaudePolicyBlock", () => {
  it("imports the shared AGENTS.md policy", () => {
    expect(renderClaudePolicyBlock()).toBe(
      "> Owned region, generated by the greenline CLI. Do not edit.\n\n@AGENTS.md",
    );
  });
});

describe("renderProjection (golden)", () => {
  it("renders the fixture corpus byte-exactly for both targets", () => {
    const projection = renderProjection(fixtureConfiguration, fixtureInstallation());
    expect(projection.map((file) => file.path)).toEqual([
      ".agents/skills/delivery-review/SKILL.md",
      ".agents/skills/delivery-review/agents/openai.yaml",
      ".agents/skills/grilling/SKILL.md",
      ".agents/skills/grilling/agents/openai.yaml",
      ".claude/skills/delivery-review/SKILL.md",
      ".claude/skills/grilling/SKILL.md",
      ".greenline/THIRD_PARTY_NOTICES.md",
      ".greenline/WORK.md",
      ".greenline/ledger/README.md",
      ".greenline/tmp/.gitignore",
      "AGENTS.md",
      "CLAUDE.md",
      "agents/openai.yaml",
    ]);
    const byPath = new Map(projection.map((file) => [file.path, file.kind]));
    expect(byPath.get("AGENTS.md")).toBe("block");
    expect(byPath.get("CLAUDE.md")).toBe("block");
    expect(byPath.get("agents/openai.yaml")).toBe("file");
    const agentsTarget = projection.find((file) => file.path === "AGENTS.md");
    expect(agentsTarget?.key).toBe(POLICY_BLOCK_KEY);
  });

  it("is byte-stable across platforms: LF only, forward-slash paths", () => {
    const projection = renderProjection(fixtureConfiguration, fixtureInstallation());
    for (const file of projection) {
      expect(file.content).not.toContain("\r");
      expect(file.path).not.toContain("\\");
      if (file.kind === "file") {
        expect(file.content.endsWith("\n")).toBe(true);
      } else {
        // Block bodies are embedded between markers; the marker join
        // owns the surrounding newlines.
        expect(file.content.endsWith("\n")).toBe(false);
      }
    }
  });

  it("renders only the selected harness", () => {
    const projection = renderProjection(
      manifestWith({ targets: ["claude-code"] }),
      fixtureInstallation(),
    );
    const paths = projection.map((file) => file.path);
    expect(paths.some((path) => path.startsWith(".agents/"))).toBe(false);
    expect(paths.some((path) => path.startsWith(".claude/"))).toBe(true);
    expect(paths).not.toContain("agents/openai.yaml");
    expect(paths).toContain("AGENTS.md");
    expect(paths).toContain("CLAUDE.md");
  });

  it("installs every default skill without a profile or language prerequisite", () => {
    const release = fixtureInstallation({
      skills: [
        ...fixtureSkills,
        {
          name: "ponytail-review",
          description: "Review minimalism.",
          class: "stage",
          activation: "explicit",
          body: "Review.",
        },
      ],
    });
    const paths = renderProjection(manifestWith({}), release).map((file) => file.path);
    expect(paths).toContain(".agents/skills/ponytail-review/SKILL.md");
    expect(paths).toContain(".claude/skills/grilling/SKILL.md");
  });

  it("honors skill excludes everywhere at once", () => {
    const projection = renderProjection(
      manifestWith({ skills: { exclude: ["grilling"], include: [] } }),
      fixtureInstallation(),
    );
    const anyGrilling = projection.some((file) => file.path.includes("grilling"));
    expect(anyGrilling).toBe(false);
    const block = projection.find((file) => file.path === "AGENTS.md")?.content ?? "";
    // The exclusion contract governs the roster and routing rows; the
    // working-laws prose above them keeps naming its method owners.
    const roster = block.slice(block.indexOf("## Installed skills"));
    expect(roster).not.toContain("grilling");
    expect(roster).toContain("delivery-review");
  });

  it("keeps both policy blocks and the tmp gitignore even with an empty corpus", () => {
    const projection = renderProjection(fixtureConfiguration, fixtureInstallation({ skills: [] }));
    expect(projection.map((file) => file.path)).toEqual([
      ".greenline/THIRD_PARTY_NOTICES.md",
      ".greenline/WORK.md",
      ".greenline/ledger/README.md",
      ".greenline/tmp/.gitignore",
      "AGENTS.md",
      "CLAUDE.md",
    ]);
  });

  it("renders the self-ignoring tmp workspace gitignore for every target", () => {
    // The ephemeral home (operator ruling, 2026-08-29): skills scratch in
    // .greenline/tmp/<skill>/ instead of host temp dirs; the directory
    // ignores itself and only the ignore file survives a clone.
    const projection = renderProjection(fixtureConfiguration, fixtureInstallation());
    const tmp = projection.find((file) => file.path === ".greenline/tmp/.gitignore");
    expect(tmp?.kind).toBe("file");
    expect(tmp?.content).toContain("*\n!.gitignore\n");
    const claudeOnly = renderProjection(
      manifestWith({ targets: ["claude-code"] }),
      fixtureInstallation(),
    );
    expect(claudeOnly.some((file) => file.path === ".greenline/tmp/.gitignore")).toBe(true);
  });

  it("emits a deterministic projection for identical inputs", () => {
    const first = JSON.stringify(renderProjection(fixtureConfiguration, fixtureInstallation()));
    const second = JSON.stringify(renderProjection(fixtureConfiguration, fixtureInstallation()));
    expect(first).toBe(second);
  });
});

describe("displayName", () => {
  it("humanizes kebab-case skill names", () => {
    expect(displayName("grilling")).toBe("Grilling");
    expect(displayName("delivery-review")).toBe("Delivery Review");
    expect(displayName("tdd")).toBe("TDD");
  });
});

describe("renderProjection opt-in skills (ADR 0029)", () => {
  const assetSkill: SkillSource = {
    name: "map-maker",
    description: "carries a code-shaped asset tree",
    class: "stage",
    activation: "explicit",
    optIn: true,
    body: "Draw the map.",
    supportFiles: [{ path: "viewer/app.tsx", content: "export const App = () => null;" }],
  };
  const plainSkill: SkillSource = {
    name: "plain",
    description: "markdown only",
    class: "discipline",
    activation: "implicit",
    body: "Plain.",
  };

  it("leaves an opt-in skill off the disk and out of the roster unless the manifest includes it", () => {
    const files = renderProjection(
      manifestWith({}),
      fixtureInstallation({ skills: [assetSkill, plainSkill] }),
    );
    const paths = files.map((f) => f.path);
    expect(paths).not.toContain(".claude/skills/map-maker/SKILL.md");
    expect(paths).not.toContain(".claude/skills/map-maker/viewer/app.tsx");
    expect(paths).toContain(".claude/skills/plain/SKILL.md");
    const block = files.find((f) => f.path === "AGENTS.md")?.content ?? "";
    expect(block).not.toContain("map-maker");
  });

  it("installs an opt-in skill, assets and all, when the manifest's include list names it", () => {
    const files = renderProjection(
      manifestWith({ skills: { exclude: [], include: ["map-maker"] } }),
      fixtureInstallation({ skills: [assetSkill, plainSkill] }),
    );
    const paths = files.map((f) => f.path);
    expect(paths).toContain(".claude/skills/map-maker/SKILL.md");
    expect(paths).toContain(".agents/skills/map-maker/viewer/app.tsx");
    const block = files.find((f) => f.path === "AGENTS.md")?.content ?? "";
    expect(block).toContain("map-maker");
  });

  it("keeps exclude above include: an included skill that is also excluded stays out", () => {
    const files = renderProjection(
      manifestWith({ skills: { exclude: ["map-maker"], include: ["map-maker"] } }),
      fixtureInstallation({ skills: [assetSkill] }),
    );
    expect(files.map((f) => f.path)).not.toContain(".claude/skills/map-maker/SKILL.md");
  });
});

describe("preserved support trees and external guidance", () => {
  it("keeps a selected method's complete support tree regardless of repository language", () => {
    const release = fixtureInstallation({
      skills: [
        {
          name: "method",
          description: "A coherent method.",
          class: "discipline",
          activation: "implicit",
          body: "Read the examples.",
          supportFiles: [
            { path: "references/go.md", content: "Go example.\n" },
            { path: "references/typescript.md", content: "TypeScript example.\n" },
          ],
        },
      ],
    });
    const files = renderProjection(manifestWith({}), release);
    expect(
      files.find((file) => file.path === ".agents/skills/method/references/go.md")?.content,
    ).toBe("Go example.\n");
    expect(
      files.find((file) => file.path === ".claude/skills/method/references/typescript.md")?.content,
    ).toBe("TypeScript example.\n");
  });
});
